# Generated by Django 4.0.5 on 2022-12-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_rename_owner_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Description',
            field=models.CharField(default='Please describe your estate here. You may also justify the price of your estate here.', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Amenities',
            field=models.CharField(default='Bathroom', max_length=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Bathroom',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Bedroom',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Build_Area',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Contact_mail',
            field=models.EmailField(default='admin@gmail.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Face',
            field=models.CharField(default='East', max_length=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Image',
            field=models.ImageField(max_length=254, upload_to=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Parking',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Road_Type',
            field=models.CharField(default='Concrete', max_length=30),
        ),
    ]
