# Generated by Django 4.0.5 on 2022-12-31 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_listing_description_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
