# Generated by Django 4.0.5 on 2023-02-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_listing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Age',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='Owner',
            field=models.CharField(default='', max_length=30),
        ),
    ]
