# Generated by Django 4.0.5 on 2023-02-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_listing_owner_alter_listing_title_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Title',
            field=models.CharField(default='House on Sale', max_length=30),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
